zelf-regelen op overviewpage
ConductionNL/skeleton-pip pull request #35
Opened 2022-05-09 14:36 UTC by hghanbari

2022-05-10 09:56 UTC, lencodes requested changes
Very nice @hghanbari.

I did leave a few comments.

Final result should look like this (see how there's margins between the cards and there's less margin underneath "Zelf regelen" and the start of the cards):

![image](https://user-images.githubusercontent.com/66552932/167602339-70ea701a-9386-4f1a-90b7-e857e6784700.png)

2022-05-10 09:56 UTC, lencodes commented on pwa/src/pages/self-services.tsx
> +export default SelfServices;
This file isn't prettified.

2022-05-10 09:56 UTC, lencodes commented on pwa/src/templates/templateParts/overview/OverviewTemplate.module.css
> +.container > .grid ,
This `.container > .grid` shouldn't have the rules defined in this block.

There's a css property called `display: grid;`. Since you're calling it a grid (and it should be a grid, so that's good) it should also be a `display: grid;`.

2022-05-10 09:56 UTC, lencodes commented on pwa/src/templates/templateParts/overview/OverviewTemplate.module.css
> +.container > .grid ,
So the `.grid` should get something like:

```
display: grid;
grid-template-columns: 1fr 1fr 1fr;
grid-gap: ...px;
```

2022-05-10 09:56 UTC, lencodes commented on pwa/src/templates/templateParts/overview/OverviewTemplate.tsx
> +          <Heading3>{t("Self services")}</Heading3>
Self service*

2022-05-10 09:56 UTC, lencodes commented on pwa/src/templates/templateParts/overview/OverviewTemplate.tsx
> +          <Heading3>{t("Self services")}</Heading3>
It's a verb, not a plural.

2022-05-10 09:56 UTC, lencodes commented on pwa/src/translations/nl.ts
> +  "Show all services": "Bekijk alle regelen",
Bekijk alle e-diensten*

2022-05-10 09:56 UTC, lencodes commented on pwa/src/translations/nl.ts
> +  "Show all services": "Bekijk alle regelen",
(I can see how these translations are confusing 😝 )

2022-05-10 09:56 UTC, lencodes commented on pwa/src/templates/templateParts/overview/OverviewTemplate.tsx
> +      </div>
Because you've added this grid outside of the `.services` div, it's messing up the margins in the layout.

2022-05-11 07:59 UTC, remko48 approved these changes

2022-05-11 08:00 UTC, merged