HorizontalImageCard component voor landingpage
ConductionNL/skeleton-pip pull request #57
Opened 2022-05-19 09:13 UTC by hghanbari

2022-05-20 05:40 UTC, lencodes requested changes
Looks good, did leave some comments 👍🏼

2022-05-20 05:40 UTC, lencodes commented on pwa/src/components/card/HorizontalImageCard/HorizontalImageCard.module.css
> +  flex-flow: column nowrap;
Instead of using the `flex-flow` property here, I suggest using:

`flex-direction: column;`

2022-05-20 05:40 UTC, lencodes commented on pwa/src/components/card/HorizontalImageCard/HorizontalImageCard.module.css
> +}
You already have a padding on the image, I don't think you need another spacing.

2022-05-20 05:40 UTC, lencodes commented on pwa/src/components/card/HorizontalImageCard/HorizontalImageCard.module.css
> +  border: var(--nlportal-document-border, 1px solid);
You can make this border completely using only available design tokens (so `1px` and `solid` shouldn't be hardcoded here).

2022-05-20 05:40 UTC, lencodes commented on pwa/src/components/card/HorizontalImageCard/HorizontalImageCard.module.css
> +  justify-content: space-between;
Since container has only one child, `justify-content: space-between;` is not doing anything.

2022-05-20 05:40 UTC, lencodes commented on pwa/src/components/card/HorizontalImageCard/HorizontalImageCard.tsx
> +      <div className={styles.content} onClick={() => navigate(link.href)}>
I think this `.content` wrapper is redundant. Since it's the only child within `.container` I think you could just set the `onClick` onto `.container` and move the `.content` styling to `.container` and it'll work exactly the same (but then without the extra wrapper).

2022-05-20 05:40 UTC, lencodes commented on pwa/src/components/card/HorizontalImageCard/HorizontalImageCard.tsx
> +        <div className={styles.context}>
I think this `.context` should be named differently (_what_ is this `div` containing?).

E.g.: `.titleAndIcon`.

2022-05-20 05:40 UTC, lencodes commented on pwa/src/styling/design-tokens/conduction-design-tokens.css
> +  --conduction-component-HorizontalImageCard-block: 400px;
This rule can be removed (see other feedback regarding it).

2022-05-20 05:40 UTC, lencodes commented on pwa/src/components/card/HorizontalImageCard/HorizontalImageCard.module.css
> +  width: var(--conduction-component-HorizontalImageCard-block);
We (almost) never want to set a fixed width (or height) within a component.

Right now, if we would want to implement this card somewhere it has to be 600px or 200px, we cannot. Because the component is setting its own size. 

We can pass a `layoutClassName` for exactly this reason. This way, the place (the context) _where we implement a component_ we can set it's layout (e.g. width and other sizes).

This rule should be removed, and the right size should be set within the implementation layer (in this case: `LandingTemplate`).

2022-05-20 05:40 UTC, lencodes commented on pwa/src/templates/landing/LandingTemplate.tsx
> +              label: t("Login with DigID"),
DigiD*

2022-05-20 05:40 UTC, lencodes commented on pwa/src/components/card/HorizontalImageCard/HorizontalImageCard.module.css
> +  width: var(--conduction-component-HorizontalImageCard-block);
Note: the easiest way right now to set the width of these cards properly would be in `LandingTemplate.module.css`.  There's a `grid-column-template` set to `1fr 1fr 1fr`. Changing this to `1fr 1fr` fixes the issue 👍🏼

2022-05-20 05:40 UTC, lencodes commented on pwa/src/components/card/HorizontalImageCard/HorizontalImageCard.tsx
> +    <div className={clsx(styles.container, [layoutClassName && layoutClassName])}>
Once you've set the `onClick` on this `div` it'd be nice to have a visual feedback that this entire block is clickable. You can do this with: `cursor: pointer;`.

2022-05-20 05:40 UTC, lencodes commented on pwa/src/styling/design-tokens/conduction-design-tokens.css
> +  --conduction-component-HorizontalImageCard-font-size: 25px;
I think the denhaag design tokens will contain something for font-sizes. Probably best to use those.

2022-05-20 05:40 UTC, lencodes commented on pwa/src/styling/design-tokens/conduction-design-tokens.css
> +  --conduction-component-HorizontalImageCard-icon-size: 80px;
All design tokens should be lowercase and hyphen separated.

2022-05-23 09:10 UTC, hghanbari commented on pwa/src/styling/design-tokens/conduction-design-tokens.css
> +  --conduction-component-HorizontalImageCard-font-size: 25px;
I can not find the exact font size and it. This was the closest (--nlportal-meta-icon-line-height: 1.5rem; )

2022-05-24 06:20 UTC, lencodes approved these changes
Nicely done @hghanbari, I've implemented my last bits of feedback and am merging this PR now.

2022-05-24 06:20 UTC, merged