ImageAndDetailsCard component
ConductionNL/skeleton-pip pull request #60
Opened 2022-05-19 14:20 UTC by hghanbari

2022-05-20 05:59 UTC, lencodes requested changes
Good start 👍🏼 

Important note on this component: you're setting hardcoded values within the component, this way it cannot be implemented in any context. Also, you're not yet managing the image size, this way the image can (and will) become distorted.

2022-05-20 05:59 UTC, lencodes commented on pwa/src/components/card/imageAndDetailsCard/ImageAndDetailsCard.module.css
> +  width: var(--conduction-component-ImageAndDetailsCard-block-width);
We should never set the width of a component in the component itself. Right now, we're creating a fixed width component, making it hard to implement elsewhere.

For example, the width is now (effectively) 288px. What happens when we want to include this card somewhere where it could easily fill 300px? Not possible right now.

2022-05-20 05:59 UTC, lencodes commented on pwa/src/components/card/imageAndDetailsCard/ImageAndDetailsCard.module.css
> +  border: var(--nlportal-document-border, 1px solid);
There are design tokens for every value within this border.

2022-05-20 05:59 UTC, lencodes commented on pwa/src/components/card/imageAndDetailsCard/ImageAndDetailsCard.module.css
> +  font-weight: var(--conduction-component-ImageAndDetailsCard-font-weight);
There's probably a den-haag design token for this.

2022-05-20 05:59 UTC, lencodes commented on pwa/src/components/card/imageAndDetailsCard/ImageAndDetailsCard.module.css
> +  font-size: var(--conduction-component-ImageAndDetailsCard-font-size-date);
There's probably a den-haag design token for this.

2022-05-20 05:59 UTC, lencodes commented on pwa/src/components/card/imageAndDetailsCard/ImageAndDetailsCard.module.css
> +  font-size: var(--conduction-component-ImageAndDetailsCard-font-size);
There's probably a den-haag design token for this.

2022-05-20 05:59 UTC, lencodes commented on pwa/src/components/card/imageAndDetailsCard/ImageAndDetailsCard.module.css
> +  margin-bottom: var(--denhaag-space-block-md);
You're missing the modern declarations here: `margin-block-start` and `margin-block-end`.

2022-05-20 05:59 UTC, lencodes commented on pwa/src/components/card/imageAndDetailsCard/ImageAndDetailsCard.module.css
> +  height: var(--conduction-component-ImageAndDetailsCard-block-height);
Because you're setting hardcoded values for the height and width and don't have any checks for the `object-fit` or `aspect-ratio`, this image will break.

See how this photo is losing it's aspect ratio?

![image](https://user-images.githubusercontent.com/66552932/169459564-aef804ba-335a-49b8-a660-c6a464ba98c8.png)
![image](https://user-images.githubusercontent.com/66552932/169459594-078b2d50-2c4e-437f-81d9-d14934a2f8ef.png)

2022-05-20 05:59 UTC, lencodes commented on pwa/src/components/card/imageAndDetailsCard/ImageAndDetailsCard.tsx
> +  image?: JSX.Element;
Since this is a `ImageAndDetailsCard`, I'd expect the `image` prop to be required.

2022-05-20 05:59 UTC, lencodes commented on pwa/src/components/card/imageAndDetailsCard/ImageAndDetailsCard.tsx
> +      <div className={styles.content} onClick={() => navigate(link.href)}>
I don't think we need this `.content` wrapper. If we move the css of `.content` to `.container` as well as the onClick, the outcome would be the same.

2022-05-20 05:59 UTC, lencodes commented on pwa/src/components/card/imageAndDetailsCard/ImageAndDetailsCard.tsx
> +    <div className={clsx(styles.container, [layoutClassName && layoutClassName])}>
Since the entire block is clickable, it might be a nice feature to ass `cursor: pointer;` to the block so that there's a visual feedback.

2022-05-20 05:59 UTC, lencodes commented on pwa/src/components/card/imageAndDetailsCard/ImageAndDetailsCard.tsx
> +        <div className={styles.context}>
I don't think `.context` is a descriptive className. _What_ is within this block? 

E.g. `.content`.

2022-05-20 05:59 UTC, lencodes commented on pwa/src/styling/design-tokens/conduction-design-tokens.css
> +  --conduction-component-ImageAndDetailsCard-block-width: 18rem;
We cannot ever set a hardcoded width for a component. Therefore, this token can be removed.

2022-05-20 05:59 UTC, lencodes commented on pwa/src/styling/design-tokens/conduction-design-tokens.css
> +  --conduction-component-ImageAndDetailsCard-font-size-date: 0.9rem;
Den Haag probably has a similar design token for this.

2022-05-20 05:59 UTC, lencodes commented on pwa/src/styling/design-tokens/conduction-design-tokens.css
> +  --conduction-component-ImageAndDetailsCard-block-height: 10rem;
We cannot ever set a hardcoded height for a component. Therefore, this token can be removed.

2022-05-20 05:59 UTC, lencodes commented on pwa/src/styling/design-tokens/conduction-design-tokens.css
> +  --conduction-component-ImageAndDetailsCard-font-size:  1rem;
Den Haag probably has a similar design token for this.

2022-05-20 05:59 UTC, lencodes commented on pwa/src/styling/design-tokens/conduction-design-tokens.css
> +  --conduction-component-ImageAndDetailsCard-font-weight: bold;
Den Haag probably has a similar design token for this.

2022-05-20 05:59 UTC, lencodes commented on pwa/src/templates/templateParts/overview/OverviewTemplate.tsx
>            />
We're not actually going to implement this card component here. It's fine to have this for testing purposes. However, do not merge this into development.

This card will be used within the `products` and `news` pages (which are not yet available on your branch).

2022-05-23 14:24 UTC, hghanbari commented on pwa/src/templates/templateParts/overview/OverviewTemplate.tsx
>            />
I wait for feature/GW-788/PDC-PUB mergen and than i can tested.

2022-05-24 06:33 UTC, lencodes requested changes
Hi @hghanbari, I think it will be best when we pair-program my feedback on this pull request.

As of now, this component is **not** robust enough to merge it with development.

A few examples of how this component can be implemented (which is not intended):

![image](https://user-images.githubusercontent.com/66552932/169963868-838df22d-60b5-4435-8b4b-f1064b0418b5.png)

![image](https://user-images.githubusercontent.com/66552932/169964131-d9f1f94a-af63-4731-aa42-c6885ede6e13.png)

2022-05-24 10:09 UTC, lencodes commented
@hghanbari after the refinement it became clear we'll need this component earlier than that we could've pair-programmed it. Therefore, I've implemented the required changes and I'm merging this pull request now.

2022-05-24 10:09 UTC, merged